#pragma once

#include <map>
#include <string>
#include <vector>

static const std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string>>> s_legacyMovesMap
{
	{"Venusaur", {{},{"Frenzy Plant"}}},
	{"Charizard", {{"Ember", "Wing Attack", "Dragon Breath"}, {"Blast Burn", "Flamethrower"}}},
	{"Blastoise", {{},{"Hydro Cannon"}}},
	{"Beedrill", {{"Bug Bite"},{"Drill Run"}}},
	{"Raticate", {{},{}}},
	{"Fearow", {{},{"Twister"}}},
	{"Arbok", {{},{}}},
	{"Pikachu", {{"Present"},{"Surf", "Thunder"}}},
	{"Sandslash", {{},{"Night Slash"}}},
	{"Ninetales", {{"Ember"},{"Fire Blast", "Flamethrower"}}},
	{"Wigglytuff", {{},{}}},
	{"Dugtrio", {{"Mud Shot"},{}}},
	{"Persian", {{},{"Night Slash"}}},
	{"Arcanine", {{"Bite"},{"Bulldoze"}}},
	{"Alakazam", {{"Counter"},{"Dazzling Gleam", "Psychic"}}},
	{"Machamp", {{"Karate Chop"},{"Stone Edge", "Submission", "Payback"}}},
	{"Alolan Golem", {{"Rollout"},{}}},
	{"Galarian Slowpoke", {{},{}}},
	{"Magneton", {{},{}}},
	{"Dodrio", {{},{"Air Cutter"}}},
	{"Gengar", {{"Lick"},{"Sludge Wave", "Dark Pulse", "Psychic", "Shadow Punch"}}},
	{"Hypno", {{},{"Psyshock"}}},
	{"Exeggutor", {{"Zen Headbutt"},{}}},
	{"Hitmonchan", {{"Rock Smash"},{"Brick Break"}}},
	{"Weezing", {{"Acid"},{}}},
	{"Rhydon", {{},{"Megahorn"}}},
	{"Starmie", {{"Quick Attack", "Tackle"},{"Psybeam"}}},
	{"Magmar", {{},{}}},
	{"Gyarados", {{"Dragon Tail"},{"Dragon Pulse", "Aqua Tail"}}},
	{"Vaporeon", {{},{"Last Resort", "Scald"}}},
	{"Jolteon", {{},{"Last Resort", "Zap Cannon"}}},
	{"Flareon", {{},{"Heat Wave", "Last Resort", "Superpower"}}},
	{"Omastar", {{"Rock Throw"},{"Rock Slide"}}},
	{"Kabutops", {{"Fury Cutter"},{}}},
	{"Snorlax", {{"Yawn"},{}}},
	{"Articuno", {{},{"Hurricane"}}},
	{"Zapdos", {{"Thunder Shock"},{}}},
	{"Moltres", {{},{"Sky Attack"}}},
	{"Dragonite", {{},{"Dragon Pulse", "Draco Meteor"}}},
	{"Mewtwo", {{},{"Shadow Ball", "Hyper Beam", "Psystrike"}}},
	{"Ledian", {{},{}}},
	{"Azumarill", {{},{}}},
	{"Sudowoodo", {{},{}}},
	{"Jumpluff", {{},{"Acrobatics"}}},
	{"Yanma", {{},{}}},
	{"Espeon", {{},{"Last Resort", "Shadow Ball"}}},
	{"Umbreon", {{},{"Last Resort"}}},
	{"Houndoom", {{},{}}},
	{"Hitmontop", {{},{}}},
	{"Blissey", {{},{}}},
	{"Tyranitar", {{"Smack Down"},{}}},
	{"Lugia", {{},{"Aeroblast"}}},
	{"Sceptile", {{},{"Frenzy Plant"}}},
	{"Blaziken", {{},{"Blast Burn", "Stone Edge"}}},
	{"Swampert", {{},{"Hydro Cannon"}}},
	{"Swellow", {{},{}}},
	{"Gardevoir", {{},{"Synchronoise"}}},
	{"Exploud", {{},{}}},
	{"Aggron", {{},{}}},
	{"Wailord", {{},{}}},
	{"Flygon", {{},{"Earth Power"}}},
	{"Solrock", {{},{}}},
	{"Crawdaunt", {{},{}}},
	{"Cradily", {{},{}}},
	{"Milotic", {{},{}}},
	{"Salamence", {{},{"Outrage"}}},
	{"Beldum", {{},{}}},
	{"Metagross", {{},{"Meteor Mash"}}},
	{"Regirock", {{},{"Earthquake"}}},
	{"Regice", {{},{"Thunder"}}},
	{"Kyogre", {{},{"Origin Pulse"}}},
	{"Groudon", {{},{"Fire Punch", "Precipice Blades"}}},
	{"Rayquaza", {{},{"Hurricane", "Breaking Swipe"}}},
	{"Torterra", {{},{"Frenzy Plant"}}},
	{"Infernape", {{},{"Blast Burn"}}},
	{"Empoleon", {{},{"Hydro Cannon"}}},
	{"Staraptor", {{"Gust"},{}}},
	{"Rampardos", {{},{}}},
	{"Drifblim", {{},{}}},
	{"Lopunny", {{},{}}},
	{"Skuntank", {{},{}}},
	{"Gabite", {{},{}}},
	{"Garchomp", {{},{"Earth Power"}}},
	{"Drapion", {{},{}}},
	{"Toxicroak", {{},{}}},
	{"Rhyperior", {{},{"Rock Wrecker"}}},
	{"Tangrowth", {{},{}}},
	{"Togekiss", {{},{"Aura Sphere"}}},
	{"Yanmega", {{},{}}},
	{"Leafeon", {{"Bullet Seed"},{"Last Resort"}}},
	{"Glaceon", {{},{"Last Resort", "Water Pulse"}}},
	{"Mamoswine", {{},{"Ancient Power"}}},
	{"Uxie", {{},{}}},
	{"Mesprit", {{},{}}},
	{"Azelf", {{},{}}},
	{"Dialga", {{},{}}},
	{"Palkia", {{},{}}},
	{"Heatran", {{},{"Magma Storm"}}},
	{"Regigigas", {{},{}}},
	{"Giratina (Altered Forme)", {{},{"Shadow Force"}}},
	{"Cresselia", {{},{"Grass Knot"}}},
	{"Serperior", {{},{"Frenzy Plant"}}},
	{"Emboar", {{},{"Blast Burn"}}},
	{"Stoutland", {{},{}}},
	{"Unfezant", {{},{}}},
	{"Swoobat", {{},{}}},
	{"Excadrill", {{},{}}},
	{"Seismitoad", {{},{}}},
	{"Throh", {{},{}}},
	{"Lilligant", {{},{}}},
	{"Sawsbuck", {{},{}}},
	{"Haxorus", {{},{"Breaking Swipe"}}},
	{"Braviary", {{},{}}},
	{"Hydreigon", {{},{"Brutal Swing"}}},
	{"Larvesta", {{},{}}},
	{"Landorus (Incarnate Forme)", {{},{}}},
	{"Chesnaught", {{},{"Frenzy Plant"}}},
	{"Delphox", {{},{"Blast Burn"}}},
	{"Greninja", {{},{"Hydro Cannon"}}},
	{"Diggersby", {{},{}}},
	{"Pyroar", {{},{}}},
	{"Swirlix", {{},{}}},
	{"Dragalge", {{},{}}},
	{"Tyrantrum", {{},{}}},
	{"Sylveon", {{},{"Last Resort", "Psyshock"}}},
	{"Xerneas", {{"Geomancy"},{}}},
	{"Yveltal", {{},{"Oblivion Wing"}}},
	{"Zygarde (10% Forme)", {{},{}}},
	{"Primarina", {{},{}}},
	{"Gumshoos", {{},{}}},
	{"Vikavolt", {{},{}}},
	{"Lurantis", {{},{}}},
	{"Tsareena", {{},{}}},
	{"Golisopod", {{},{}}},
	{"Tapu Bulu", {{},{}}},
	{"Tapu Fini", {{},{}}},
	{"Cosmog", {{},{}}},
	{"Zacian - Hero of Many Battles", {{},{}}},
	{"Zamazenta - Hero of Many Battles", {{},{}}},
	{"Regieleki", {{},{}}},
	{"Regidrago", {{},{}}},
};
