#pragma once

#include <map>
#include <string>
#include <vector>

static const std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string>>> s_legacyMovesMap
{
	{"Venusaur", {{},{"Frenzy Plant"}}},
	{"Charizard", {{"Ember", "Wing Attack", "Dragon Breath"}, {"Blast Burn", "Flamethrower"}}},
	{"Blastoise", {{},{"Hydro Cannon"}}},
	{"Beedrill", {{"Bug Bite"},{"Drill Run"}}},
	{"Raticate", {{},{}}},
	{"Fearow", {{},{"Twister"}}},
	{"Arbok", {{},{}}},
	{"Pikachu", {{"Present"},{"Surf", "Thunder"}}},
	{"Sandslash", {{},{"Night Slash"}}},
	{"Ninetales", {{"Ember"},{"Fire Blast", "Flamethrower"}}},
	{"Wigglytuff", {{},{}}},
	{"Dugtrio", {{"Mud Shot"},{}}},
	{"Persian", {{},{"Night Slash"}}},
	{"Arcanine", {{"Bite"},{"Bulldoze"}}},
	{"Alakazam", {{"Counter"},{"Dazzling Gleam", "Psychic"}}},
	{"Machamp", {{"Karate Chop"},{"Stone Edge", "Submission", "Payback"}}},
	{"Alolan Golem", {{"Rollout"},{}}},
	{"Galarian Slowpoke", {{},{}}},
	{"Magneton", {{},{}}},
	{"Dodrio", {{},{"Air Cutter"}}},
	{"Gengar", {{"Lick"},{"Sludge Wave", "Dark Pulse", "Psychic", "Shadow Punch"}}},
	{"Hypno", {{},{"Psyshock"}}},
	{"Exeggutor", {{"Zen Headbutt"},{}}},
	{"Hitmonchan", {{"Rock Smash"},{"Brick Break"}}},
	{"Weezing", {{"Acid"},{}}},
	{"Rhydon", {{},{"Megahorn"}}},
	{"Starmie", {{"Quick Attack", "Tackle"},{"Psybeam"}}},
	{"Magmar", {{},{}}},
	{"Gyarados", {{"Dragon Tail"},{"Dragon Pulse", "Aqua Tail"}}},
	{"Vaporeon", {{},{"Last Resort", "Scald"}}},
	{"Jolteon", {{},{"Last Resort", "Zap Cannon"}}},
	{"Flareon", {{},{"Heat Wave", "Last Resort", "Superpower"}}},
	{"Omastar", {{"Rock Throw"},{"Rock Slide"}}},
	{"Kabutops", {{"Fury Cutter"},{}}},
	{"Snorlax", {{"Yawn"},{}}},
	{"Dragonite", {{},{"Dragon Pulse", "Draco Meteor"}}},
	{"Ledian", {{},{}}},
	{"Azumarill", {{},{}}},
	{"Jumpluff", {{},{"Acrobatics"}}},
	{"Yanma", {{},{}}},
	{"Espeon", {{},{"Last Resort", "Shadow Ball"}}},
	{"Umbreon", {{},{"Last Resort"}}},
	{"Houndoom", {{},{}}},
	{"Hitmontop", {{},{}}},
	{"Blissey", {{},{}}},
	{"Tyranitar", {{"Smack Down"},{}}},
	{"Sceptile", {{},{"Frenzy Plant"}}},
	{"Blaziken", {{},{"Blast Burn", "Stone Edge"}}},
	{"Swampert", {{},{"Hydro Cannon"}}},
	{"Swellow", {{},{}}},
	{"Gardevoir", {{},{"Synchronoise"}}},
	{"Exploud", {{},{}}},
	{"Aggron", {{},{}}},
	{"Wailord", {{},{}}},
	{"Flygon", {{},{"Earth Power"}}},
	{"Solrock", {{},{}}},
	{"Crawdaunt", {{},{}}},
	{"Cradily", {{},{}}},
	{"Milotic", {{},{}}},
	{"Salamence", {{},{"Outrage"}}},
	{"Empoleon", {{},{"Hydro Cannon"}}},
	{"Staraptor", {{"Gust"},{}}},
	{"Rampardos", {{},{}}},
	{"Drifblim", {{},{}}},
	{"Lopunny", {{},{}}},
	{"Skuntank", {{},{}}},
	{"Garchomp", {{},{"Earth Power"}}},
	{"Drapion", {{},{}}},
	{"Toxicroak", {{},{}}},
	{"Rhyperior", {{},{"Rock Wrecker"}}},
	{"Tangrowth", {{},{}}},
	{"Togekiss", {{},{"Aura Sphere"}}},
	{"Yanmega", {{},{}}},
	{"Leafeon", {{"Bullet Seed"},{"Last Resort"}}},
	{"Glaceon", {{},{"Last Resort", "Water Pulse"}}},
	{"Mamoswine", {{},{"Ancient Power"}}},
	{"Serperior", {{},{"Frenzy Plant"}}},
	{"Emboar", {{},{"Blast Burn"}}},
	{"Stoutland", {{},{}}},
	{"Unfezant", {{},{}}},
	{"Swoobat", {{},{}}},
	{"Excadrill", {{},{}}},
	{"Seismitoad", {{},{}}},
	{"Throh", {{},{}}},
	{"Lilligant", {{},{}}},
	{"Sawsbuck", {{},{}}},
	{"Haxorus", {{},{"Breaking Swipe"}}},
	{"Braviary", {{},{}}},
	{"Hydreigon", {{},{"Brutal Swing"}}},
	{"Larvesta", {{},{}}},
	{"Chesnaught", {{},{"Frenzy Plant"}}},
	{"Delphox", {{},{"Blast Burn"}}},
	{"Greninja", {{},{"Hydro Cannon"}}},
	{"Diggersby", {{},{}}},
	{"Pyroar", {{},{}}},
	{"Swirlix", {{},{}}},
	{"Dragalge", {{},{}}},
	{"Tyrantrum", {{},{}}},
	{"Sylveon", {{},{"Last Resort", "Psyshock"}}},
	{"Primarina", {{},{}}},
	{"Gumshoos", {{},{}}},
	{"Vikavolt", {{},{}}},
	{"Lurantis", {{},{}}},
	{"Golisopod", {{},{}}},
};
